root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/notification-service ./cmd/main.go"
bin = "./tmp/notification-service"
include_ext = ["go", "toml"]
exclude_dir = ["tmp", "vendor"]
include_dir = ["."]

[log]
color = true

[misc]
reload_on_config_change = true