root = "/app"
working_dir = "/app/backend/api-gateway"

[build]
cmd = "go build -o ./tmp/api-gateway ./cmd/main.go"
bin = "./tmp/api-gateway"

include_ext = ["go", "toml", "proto"]
exclude_dir = ["tmp"]

include_dir = ["backend/api-gateway", "backend/proto"]

[log]
color = true
[misc]
reload_on_config_change = true