root = "/app"
working_dir = "/app/backend/api-gateway"

[build]
cmd = "swag init -g main.go --dir ./cmd,./handlers --parseDependency --parseInternal && go build -o ./tmp/main ./cmd/main.go"
bin = "./tmp/api-gateway"

include_ext = ["go", "toml", "proto"]
exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs"]

include_dir = ["backend/api-gateway", "backend/proto"]
exclude_regex = ["_test.go", "docs/.*"]

[log]
color = true
[misc]
reload_on_config_change = true